---
title: "Formulas e Notacoes - Amostragem"
author: "Davi Wentrick Feijó"
date: "2024-04-06"
output: 
  rmdformats::downcute:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: true
    highlight: tango
    toc_depth : 4
  html_document:
    toc: false
    toc_depth: 5
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Conceitos Básicos

### População ou Universo - $U$

É o conjunto de todas as unidades elementares de interesse, podendo ser denotada por: 

$$
U=\{1,2, \ldots, N\}
$$
onde $N$ é o tamanho fixo e, as vezes, desconhecido da população.

### Característica(s) de interesse - $Y_i$

É a nomenclatura para denotar a variável ou o vetor de informações associado a cada elemento da população.

$$
Y_i \ \ \text{com} \ \ i \in U
$$

### Amostra - $s$,$S$ e $S_n$

Uma sequência qualquer de $n$ unidades de $U$ é denominada uma amostra aleatória de $U$, isto é,

$$
s=\left(k_1, k_2, \ldots, k_n\right)
$$
tal que $k_i \in U$

Seja $S(U)$, ou simplesmente $S$, o conjunto de todas as amostras (sequências ordenadas) de $U$, de qualquer tamanho. E seja $S_n(U)$ a subclasse de todas as amostras de tamanho $n$.

*  $S(U)$ é denominado espaço amostral.

#### Exemplo:

Seja U = {1, 2, 3}. Então,

$$
\begin{gathered}
S(U)=\{(1),(2),(3),(1,1),(1,2),(1,3),(2,1),
\ldots,(2,2,1,3,2), \ldots\}
\end{gathered}
$$

Ou seja $S(U)$ contem todas as possiveis amostras que podem ser retiradas de todos os $n$ possiveis

$$
\begin{gathered}
S_2(U)=\{(1,1),(1,2),(1,3),(2,1),(2,2),(2,3),(3,1),(3,2),(3,3)\}
\end{gathered}
$$

Quando queremos todas as amostras de tamanho 2 (n=2) usamos $S_2(U)$

### Parametros de interesse

* Total populacional: $\tau=\sum_{i=1}^N Y_i$

* Média populacional: $\mu=\frac{\tau}{N}=\frac{1}{N} \sum_{i=1}^N Y_i$

* Proporção populacional: $p=\frac{1}{N} \sum_{i=1}^N Y_i$, quando $Y_i \in 0,1, \forall i$

* Variância populacional: $\sigma^2=\frac{1}{N} \sum_{i=1}^N\left(Y_i-\mu\right)^2$

* Covariância populacional: $\sigma_{X Y}=\frac{1}{N} \sum_{i=1}^N\left(X_i-\mu_X\right)\left(Y_i-\mu_Y\right)$

* Correlação populacional: $\rho_{X Y}=\frac{\sigma_{X Y}}{\sigma_X \sigma_Y}$

* Razão populacional: $R=\frac{\tau_Y}{\tau_X}=\frac{\mu_Y}{\mu_X}$

* Razão média populacional: $\bar{R}=\frac{1}{N} \sum_{i=1}^N \frac{Y_i}{X_i}$


### Planejamento Amostral

Mecanismo que associa a probabilidade de ocorrência de cada possível amostra, $P(s)$ definida em $S(U)$, i.e.,

$$
P(.): S(U) \rightarrow[0,1]
$$

satisfazendo

$$
P(s) \geq 0, \forall s \in S(U)
$$

e tal que

$$
\sum_{s, s \in S} P(s)=1
$$

#### Exemplo:

Plano Amostral A: Sorteia-se com igual probabilidade um elemento de $U$ e anota-se a unidade sorteada. Este elemento é devolvido à população e sorteia-se um segundo elemento do mesmo modo.

$$
\begin{aligned}
& S_A(U)=\{11,12,13,21,22,23,31,32,33\} \\
& P_A=\left\{\begin{array}{cl}
1 / 9, & \text { se } i \in S \\
0, & \text { se } i \notin S
\end{array}\right.
\end{aligned}
$$

### Dados da amostra $s$

Vetor ou a matriz das observações pertencentes à amostra, i.é.,

$$
\boldsymbol{d s}=\left(Y_{k 1}, Y_{k 2}, \ldots, Y_{k n}\right)=\left(Y_{k i}, k_i \in \boldsymbol{s}\right) .
$$

Quando $s$ percorre todos os pontos possíveis de um plano amostral $S_A$, tem-se um vetor aleatório

$$
\boldsymbol{d}=\boldsymbol{y}=\left(y_1, \ldots, y_i, \ldots, y_n\right)
$$
onde $y_i$ é a v.a. que indica os valores possíveis de ocorrer na i-ésima posição da amostra.

Sao dados calculados a partir da amostra, por exemplo renda media ou renda pelo numero de pessoas que trabalham. Ambos sao informacoes que podem ser calculadas a partida da amostra num contexto onde as unidades amostradas contenham essa informacao. Logo ao calcular esses dados para todas as amostras possiveis e a partir deles poderemos calcular a probabilidade de cada um ocorrer (no caso do exemplo a probabilidade de cada media ocorrer)

### Conjunto de todas as amostras possíveis

Nesse caso, tem-se um vetor (matriz) aleatório

$$
\boldsymbol{D} \boldsymbol{s}=\boldsymbol{Y}=\left(Y_1, \ldots, Y_i, \ldots, Y_n\right),
$$

em que $Y_i$ é a v.a. que representa os valores possíveis de ocorrerem na i-ésima posição da amostra.

### Estatística ou Estimador 

É qualquer função da amostra que relaciona as observações da amostra

$$
T=H(\boldsymbol{Y}), \quad t=h(\boldsymbol{y}) \text { (valor observado) }
$$

### Distribuição Amostral 

A distribuicao de uma estatística segundo um plano amostral $A$ é a distribuição de probabilidades de $H(\boldsymbol{d} \boldsymbol{s})$, definida sobre $S_A$, com função de probabilidade dada por:

$$
p_h=P_A\left(\boldsymbol{s} \in S_A ; H(\boldsymbol{d} \boldsymbol{s})=h\right)=P(h)
$$

Nesse caso uma vez que a gente ja tenha calculado todas as amostras possiveis, e depois ter calculado, por exemplo, a media de cada amostra, teremos uma nocao dos valores que podem ser assumidos nessa amostra, ai poderemos partir para calcular a probabilidade de ocorrencia de cada valor.


#### Exemplo - Plano Amostral A (AASc)

Sorteia-se com igual probabilidade um elemento de $U$ e anota-se a unidade sorteada. Este elemento é devolvido à população e sorteia-se um segundo elemento do mesmo modo.

| $s$ | 11 | 12 | 13 | 21 | 22 | 23 | 31 | 32 | 33 |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| $P(s)$ | $1 / 9$ | $1 / 9$ | $1 / 9$ | $1 / 9$ | $1 / 9$ | $1 / 9$ | $1 / 9$ | $1 / 9$ | $1 / 9$ |
| $r$ | 12,0 | 10,5 | 10,0 | 10,5 | 10,0 | 9,6 | 10,0 | 9,6 | 9,0 |


### Esperanca e Variancia 

Considere o $P A(A)$, uma estatística $H(\boldsymbol{d} s), \boldsymbol{s} \in S_A$ e seja $P(h)$ a função de probabilidade correspondente ao plano amostral. Então, o valor esperado (média) da variável $H$ será:

$$
E_A[T]=\sum h p_h
$$

e sua variância

$$
V_A[T]=\sum_h\left(h-E_A(T)\right)^2=E_A\left(T^2\right)-E_A(T)^2
$$

### Covariancia e Correlacao

Sejam T e G duas estatísticas, então a covariância e a correlação entre ambas são expressas a seguir:

$$
\begin{aligned}
& \operatorname{Cov}_A[T, G]=E_A(T, G)-E_A(T, G)^2 \\
\\
& \operatorname{Corr}_A[T, G]=\frac{\operatorname{Cov}_A[T, G]}{\sqrt{V_A[T] \cdot V_A[G]}}
\end{aligned}
$$
 
### Viés e Erro Quadratico Medio (EQM)

Um estimador $\hat{\theta}\left(d_s\right)$ é dito não viciado segundo um plano amostral $A$, se:

$$
E_A[\hat{\theta}]=\theta
$$

O viés (ou vício) do estimador $\hat{\theta}\left(d_s\right)$, segundo o plano amostral $A$, é dado por

$$
B_A[\hat{\theta}]=E_A[\hat{\theta}-\theta]=E_A[\hat{\theta}]-\theta
$$

e o Erro Quadrático Médio por

$$
E Q M_A[\hat{\theta}]=E_A[\hat{\theta}-\theta]^2=\operatorname{Var}_A[\hat{\theta}]+B_A^2[\hat{\theta}]
$$

#### Demonstracao $EQM$

$$
\begin{aligned} 
& E Q M_A[\hat{\theta}]=\operatorname{Var}_A[\hat{\theta}]+B_A^2[\hat{\theta}] \\ & E Q M_A[\hat{\theta}]=E_A(\hat{\theta}-\theta)^2 \\ 
& =E_A\left[\left(\hat{\theta}-E_A(\hat{\theta})\right)+\left(E_A(\hat{\theta})-\theta\right)\right]^2 \\ 
& =E_A\left[\hat{\theta}-E_A(\hat{\theta})\right]^2+\left(E_A(\hat{\theta})-\theta\right)^2 \\
& =\operatorname{Var}_A[\hat{\theta}]+B_A^2[\hat{\theta}]
\end{aligned} 
$$

### Amostragem Aleatória Simples - AAS

Chama-se tamanho efetivo $n(s)$ da amostra $s$ a soma das frequências das unidades populacionais na amostra, isto é,

$$
n(s)=\sum_{i=1}^N f_i(s)
$$

Chama-se tamanho fixo efetivo $v(\boldsymbol{s})$ da amostra $\boldsymbol{s}$ o número de unidades populacionais distintas presentes na amostra $s$, isto é,

$$
v(s)=\sum_{i=1}^N \delta_i(s)
$$

Indica-se por $\pi_i(A)$, a probabilidade de o $i$-ésimo elemente de $U$ pertencer à amostra segundo o planejamento $A$, e $\pi_{i j}(A)$ a probabilidade de o $i$-ésimo e $j$-ésimo elementos pertencerem simultaneamente à amostra. Deste modo,

$$
\pi_i(A)=P_A\left(\delta_i=1\right)=\sum_{\left\{s ; s \in S_A\right\}} P_A\left(\delta_i=1\right)=\sum_{\{s ; s \supset i\}} P_A(s)
$$

e

$$
\pi_{i j}(A)=P_A\left(\delta_{i j}=1\right)=\sum_{\{s ; s \supset\{i, j\}\}} P_A(s)
$$


## AASc

### Variavel $f_i$

Para o plano $AASc$ a variável $f_i$, número de vezes que a unidade $i$ aparece na amostra, segue uma distribuição binomial com parâmetros $n$ e $1/N$, denotado por

$$
f_i \sim \operatorname{Bin}\left(n ; \frac{1}{N}\right)
$$

de modo que

$$
\begin{aligned}
& E\left[f_i\right]=\frac{n}{N} \quad  \\
& \operatorname{Var}\left[f_i\right]=\frac{n}{N}\left(1-\frac{1}{N}\right) \quad \\
& \operatorname{Cov}\left[f_i, f_j\right]=-\frac{n}{N^2}, i \neq j \quad i, j=\overline{1, N} \\
& \pi_i=1-\left(1-\frac{1}{N}\right)^n \\
& \pi_{i j}=1-2\left(1-\frac{1}{N}\right)^n+\left(1-\frac{2}{N}\right)^n
\end{aligned}
$$

### Variavel $t(s)$ 

A estatística $t(s)$, total da amostra, definida por:

$$
t(s)=\sum_{i \in s} Y_i
$$

tem, para o plano $AASc$, as seguinte propriedades:

$$
\begin{gathered}
E[t]=n \mu \\
\operatorname{Var}[t]=n \sigma^2
\end{gathered}
$$

### Estimador da média populacional $\bar y$

A média amostral

$$
\bar{y}=\frac{1}{n} \sum_{i \in s} Y_i=\frac{t(s)}{n}=\hat{\mu}
$$

é um estimador não viesado da média populacional $\mu$ dentro do plano $A A S C$, e ainda

$$
\operatorname{Var}[\bar{y}]=\frac{\sigma^2}{n}
$$

### Estimador do total populacional $T(s)$

Do plano $A A S c$, a estatística

$$
T(s)=\hat{t}=N \bar{y}=\frac{N}{n} t(s)
$$

é um estimador não viesado do total populacional, com

$$
\operatorname{Var}[T]=N^2 \frac{\sigma^2}{n}
$$

### Estimador da variancia populacional $s^2$

Dentro do plano $A A S c$, a estatística

$$
s^2=\frac{1}{n-1} \sum_{i \in s}\left(Y_i-\bar{y}\right)^2
$$

é um estimador não viesado para a variância populacional $\sigma^2$.

### Estimadores para $Var(\bar y)$ e $Var(T)$

Para o plano $AASc$, a estatística

$$
\operatorname{var}[\bar{y}]=\widehat{\operatorname{Var}[\bar{y}}]=\frac{s^2}{n}
$$

é um estimador não viesado para a variância da média amostral, $\operatorname{Var}[\bar{y}]$, e

$$
\operatorname{var}[T]=\widehat{\operatorname{Var}[T]}=N^2 \frac{s^2}{n}
$$

é um estimador não viesado de $\operatorname{Var}[T]$. Tudo o que foi feito foi a substituicao da variancia populacional $(\sigma^2)$ pelo seu estimador $s^2$

### Normalidade Assintotica 

Para $n$ suficientemente grande, $\frac{\widehat{\theta}-E(\widehat{\theta})}{\sqrt{\operatorname{Var}(\widehat{\theta})}} \sim N(0,1)$
Com relação à $AASc$

$$
\frac{\bar{y}-\mu}{\sqrt{\sigma^2 / n}} \sim N(0,1) \text { e } \frac{T-\tau}{N \sqrt{\sigma^2 / n}} \sim N(0,1)
$$

### Intervalo de Confiança para a Média

Com relação à média, para $n$ suficientemente grande,

$$
P\left(\frac{|\bar{y}-\mu|}{\sqrt{\sigma^2 / n}} \leq z_\alpha\right) \cong 1-\alpha
$$

Como $\sigma^2$ é desconhecido, faz-se uso de $s^2$, então

$$
P\left(\bar{y}-z_\alpha \sqrt{s^2 / n} \leq \mu \leq \bar{y}+z_\alpha \sqrt{s^2 / n}\right) \cong 1-\alpha
$$

Onde segue que

$$
I C(\mu ;(1-\alpha) 100 \%)=\left(\bar{y}-z_\alpha \sqrt{\frac{s^2}{n}} ; \bar{y}+z_\alpha \sqrt{\frac{s^2}{n}}\right)
$$

### Determinação do Tamanho da Amostra

O objetivo determinar $n$, de modo que o estimador obtido tenha um erro máximo de estimação igual a $B$, isto é,

$$
P(|\bar{y}-\mu| \leq B) \cong 1-\alpha
$$

Mas

$$
P\left(|\bar{y}-\mu| \leq z_\alpha \sqrt{\sigma^2 / n}\right) \cong 1-\alpha
$$

Então,

$$
B=z_\alpha \sqrt{\sigma^2 / n} \rightarrow n=\frac{\sigma^2}{\left(B / z_\alpha\right)^2}
$$

Obs: O $\sigma^2$ é obtida de uma amostra piloto, de pesquisas anteriores, ou IC $(\mu ; 95 \%)=4 \sigma$.

## AASs

## AASc


